'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.4927
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class FormatoCapturaMarsAS

    '''<summary>
    '''Control ScriptManager1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Control lnkRegresar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lnkRegresar As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Control lblCadena.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblCadena As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblTienda.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblTienda As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control UpdatePanel.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents UpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Control Panel1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Control txtFrentes15.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFrentes15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvFrentes15.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvFrentes15 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvFrentes15.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvFrentes15 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtFrentes1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFrentes1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvaFrentes1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvaFrentes1 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control RequiredFieldValidator1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtFrentes2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFrentes2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvFrentes2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvFrentes2 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvFrentes2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvFrentes2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtFrentes3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFrentes3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvFrentes3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvFrentes3 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvFrentes3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvFrentes3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtFrentes4.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFrentes4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvFrentes4.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvFrentes4 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvFrentes4.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvFrentes4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtFrentes16.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFrentes16 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvFrentes16.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvFrentes16 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvFrentes16.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvFrentes16 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtFrentes5.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFrentes5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvFrentes5.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvFrentes5 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvFrentes5.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvFrentes5 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtFrentes6.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFrentes6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvFrentes6.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvFrentes6 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvFrentes6.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvFrentes6 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtFrentes7.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFrentes7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvFrentes7.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvFrentes7 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvFrentes7.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvFrentes7 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtFrentes8.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFrentes8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvFrentes8.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvFrentes8 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvFrentes8.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvFrentes8 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtFrentes9.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFrentes9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvFrentes9.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvFrentes9 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvFrentes9.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvFrentes9 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtFrentes10.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFrentes10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvFrentes10.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvFrentes10 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvFrentes10.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvFrentes10 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtFrentes11.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFrentes11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvFrentes11.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvFrentes11 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvFrentes11.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvFrentes11 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtFrentes12.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFrentes12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvFrentes12.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvFrentes12 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvFrentes12.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvFrentes12 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtFrentes13.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFrentes13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvFrentes13.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvFrentes13 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvFrentes13.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvFrentes13 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control txtFrentes14.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFrentes14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvFrentes14.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvFrentes14 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvFrentes14.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvFrentes14 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control pnlImagenes.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents pnlImagenes As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Control Panel2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Control txtAnaquel12.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtAnaquel12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvAnaquel12.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvAnaquel12 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control rvAnaquel12.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvAnaquel12 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control cmbProductoAnaquel12A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoAnaquel12A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoAnaquel12B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoAnaquel12B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoAnaquel12C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoAnaquel12C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtAnaquel11.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtAnaquel11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvAnaquel11.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvAnaquel11 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control rvanaquel11.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvanaquel11 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control cmbProductoAnaquel11A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoAnaquel11A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoAnaquel11B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoAnaquel11B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoAnaquel11C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoAnaquel11C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtAnaquel10.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtAnaquel10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvAnaquel10.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvAnaquel10 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control rvAnaquel10.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvAnaquel10 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control cmbProductoAnaquel10A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoAnaquel10A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoAnaquel10B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoAnaquel10B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoAnaquel10C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoAnaquel10C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtAnaquel9.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtAnaquel9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvAnaquel9.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvAnaquel9 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control rvAnaquel9.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvAnaquel9 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control cmbProductoAnaquel9A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoAnaquel9A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoAnaquel9B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoAnaquel9B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoAnaquel9C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoAnaquel9C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtPasillo6.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtPasillo6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvPasillo6.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvPasillo6 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control rvPasillo6.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvPasillo6 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control cmbProductoPasillo6A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoPasillo6A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoPasillo6B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoPasillo6B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoPasillo6C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoPasillo6C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtPasillo1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtPasillo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvPasillo1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvPasillo1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control rvPasillo1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvPasillo1 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control cmbProductoPasillo1A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoPasillo1A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoPasillo1B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoPasillo1B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoPasillo1C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoPasillo1C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtPasillo15.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtPasillo15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvPasillo15.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvPasillo15 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control rvPasillo15.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvPasillo15 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control cmbProductoPasillo15A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoPasillo15A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoPasillo15B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoPasillo15B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoPasillo15C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoPasillo15C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbExhibicionesPasillo1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbExhibicionesPasillo1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtExhibicionesPasillo1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtExhibicionesPasillo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvExhibicionesPasillo1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvExhibicionesPasillo1 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvExhibicionesPasillo1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvExhibicionesPasillo1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control cmbProductoExhibicionesPasillo1A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesPasillo1A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesPasillo1B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesPasillo1B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesPasillo1C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesPasillo1C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbExhibicionesPasillo2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbExhibicionesPasillo2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtExhibicionesPasillo2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtExhibicionesPasillo2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvExhibicionesPasillo2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvExhibicionesPasillo2 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvExhibicionesPasillo2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvExhibicionesPasillo2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control cmbProductoExhibicionesPasillo2A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesPasillo2A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesPasillo2B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesPasillo2B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesPasillo2C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesPasillo2C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbExhibicionesPasillo3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbExhibicionesPasillo3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtExhibicionesPasillo3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtExhibicionesPasillo3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvExhibicionesPasillo3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvExhibicionesPasillo3 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvExhibicionesPasillo3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvExhibicionesPasillo3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control cmbProductoExhibicionesPasillo3A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesPasillo3A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesPasillo3B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesPasillo3B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesPasillo3C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesPasillo3C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtCaliente1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtCaliente1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvCaliente1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvCaliente1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control rvCaliente1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvCaliente1 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control cmbProductoCaliente1A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoCaliente1A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoCaliente1B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoCaliente1B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoCaliente1C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoCaliente1C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtCaliente15.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtCaliente15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvCaliente15.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvCaliente15 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control rvCaliente15.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvCaliente15 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control cmbProductoCaliente15A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoCaliente15A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoCaliente15B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoCaliente15B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoCaliente15C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoCaliente15C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtCaliente3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtCaliente3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvCaliente3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvCaliente3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control rvCaliente3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvCaliente3 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control cmbProductoCaliente3A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoCaliente3A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoCaliente3B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoCaliente3B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoCaliente3C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoCaliente3C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtCaliente5.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtCaliente5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvCaliente5.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvCaliente5 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control rvCaliente5.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvCaliente5 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control cmbProductoCaliente5A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoCaliente5A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoCaliente5B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoCaliente5B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoCaliente5C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoCaliente5C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbExhibicionesCaliente1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbExhibicionesCaliente1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtExhibicionesCaliente1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtExhibicionesCaliente1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvExhibicionesCaliente1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvExhibicionesCaliente1 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvExhibicionesCaliente1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvExhibicionesCaliente1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control cmbProductoExhibicionesCaliente1A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesCaliente1A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesCaliente1B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesCaliente1B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesCaliente1C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesCaliente1C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbExhibicionesCaliente2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbExhibicionesCaliente2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtExhibicionesCaliente2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtExhibicionesCaliente2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvExhibicionesCaliente2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvExhibicionesCaliente2 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvExhibicionesCaliente2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvExhibicionesCaliente2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control cmbProductoExhibicionesCaliente2A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesCaliente2A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesCaliente2B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesCaliente2B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesCaliente2C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesCaliente2C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbExhibicionesCaliente3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbExhibicionesCaliente3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtExhibicionesCaliente3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtExhibicionesCaliente3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvExhibicionesCaliente3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvExhibicionesCaliente3 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvExhibicionesCaliente3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvExhibicionesCaliente3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control cmbProductoExhibicionesCaliente3A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesCaliente3A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesCaliente3B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesCaliente3B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesCaliente3C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesCaliente3C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtEntrada5.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtEntrada5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvEntrada5.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvEntrada5 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control rvEntrada5.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvEntrada5 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control cmbProductoEntrada5A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoEntrada5A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoEntrada5B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoEntrada5B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoEntrada5C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoEntrada5C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtEntrada16.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtEntrada16 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvEntrada16.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvEntrada16 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvEntrada16.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvEntrada16 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control cmbProductoEntrada16A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoEntrada16A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoEntrada16B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoEntrada16B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoEntrada16C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoEntrada16C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbExhibicionesEntrada1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbExhibicionesEntrada1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtExhibicionesEntrada1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtExhibicionesEntrada1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvExhibicionesEntrada1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvExhibicionesEntrada1 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvExhibicionesEntrada1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvExhibicionesEntrada1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control cmbProductoExhibicionesEntrada1A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesEntrada1A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesEntrada1B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesEntrada1B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesEntrada1C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesEntrada1C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbExhibicionesEntrada2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbExhibicionesEntrada2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtExhibicionesEntrada2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtExhibicionesEntrada2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvExhibicionesEntrada2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvExhibicionesEntrada2 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvExhibicionesEntrada2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvExhibicionesEntrada2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control cmbProductoExhibicionesEntrada2A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesEntrada2A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesEntrada2B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesEntrada2B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesEntrada2C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesEntrada2C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbExhibicionesEntrada3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbExhibicionesEntrada3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtExhibicionesEntrada3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtExhibicionesEntrada3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rvExhibicionesEntrada3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rvExhibicionesEntrada3 As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Control rfvExhibicionesEntrada3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvExhibicionesEntrada3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control cmbProductoExhibicionesEntrada3A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesEntrada3A As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesEntrada3B.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesEntrada3B As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmbProductoExhibicionesEntrada3C.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbProductoExhibicionesEntrada3C As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control Panel3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents Panel3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Control rfvImplementacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvImplementacion As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control lstImplementacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lstImplementacion As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''Control txtFechaImplementacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtFechaImplementacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control rfvFechaImplementacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents rfvFechaImplementacion As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Control chkMaterialPOP1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkMaterialPOP1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chkMaterialPOP5.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkMaterialPOP5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chkMaterialPOP2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkMaterialPOP2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chkMaterialPOP6.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkMaterialPOP6 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chkMaterialPOP3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkMaterialPOP3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chkMaterialPOP7.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkMaterialPOP7 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chkMaterialPOP4.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkMaterialPOP4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chkMaterialPOP8.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkMaterialPOP8 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control txtOtros.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtOtros As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control chkMaterialPOP9.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkMaterialPOP9 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control vsImplementacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents vsImplementacion As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''Control btnGuardarImplementacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents btnGuardarImplementacion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Control chkExhibidores13.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkExhibidores13 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control chkExhibidores17.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents chkExhibidores17 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Control cmbComentarios.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmbComentarios As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control txtComentarios.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtComentarios As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Control UpdatePanel1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Control vsMars.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents vsMars As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''Control UpdateProgress.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents UpdateProgress As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''Control btnGuardar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents btnGuardar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Control btnCancelar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.Button
End Class
